### ISSUE TITLE
JSON logging failing with error: jsonlog: Can't serialize #25

### ISSUE THREAD

**Issue by devamtech** [cowrie/k8s-cowrie#1] opened 2021-05-19 09:58 UTC
Hi All,

need your help

I have deployed cowrie honeypot, I am getting logs in the below format, can you please me to get logs in json format instead of a string.

2021-05-18T14:26:24.763743919Z stdout F 2021-05-18T14:26:24+0000 [stdout#info] jsonlog: Can't serialize: '{'eventid': 'cowrie.login.success', 'username': b'root', 'password': b'kumar', 'message': "login attempt [b'root'/b'kumar'] succeeded", 'sensor': 'cowrie-app-667d44f77-kcdzb', 'timestamp': '2021-05-18T14:26:24.763361Z', 'src_ip': '192.0.2.1', 'session': '24221d408f3c'}'
one latest VC, I am not getting Src_ip and user name and password fields only getting direct user details and password, old cowries has above logs but its in string format.
Can you please help me to get it in json format

I am using Cowrie Version 2.2.0

my yaml file si

> apiVersion: v1
kind: Service
metadata:
name: cowrie-lb
labels:
app: cowrie-app
spec:
selector:
app: cowrie-app
tier: honeypot
ports:
- protocol: "TCP"
port: 22
targetPort: 2222
type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
name: cowrie-app
labels:
app: cowrie-app
spec:
replicas: 4
selector:
matchLabels:
app: cowrie-app
tier: honeypot
strategy:
type: Recreate
template:
metadata:
labels:
app: cowrie-app
tier: honeypot
spec:
containers:
- image: cowrie/cowrie:latest
name: cowrie-app
ports:
- containerPort: 2222
name: cowrie-app

Many thanks in advance.

**Comment by micheloosterhof** [comment] 2021-05-22 04:06
This is a duplicate of https://github.com/cowrie/docker-cowrie/issues/26

**Closed as completed by micheloosterhof** 2021-05-22 04:07 UTC
